parameters:
    env(ACTIVATION_REQUEST_LIFETIME): 'P1D'
    passwordPeriod: '6 months'
    passwordAttempts: 6
    activationRequestLifeTime: '%env(ACTIVATION_REQUEST_LIFETIME)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    Aropixel\AdminBundle\Command\AdminAccessCommand:
        tags:
            - { name: 'console.command', command: 'aropixel:admin:setup' }


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Aropixel\AdminBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Aropixel\AdminBundle\Http\:
        resource: '../../Http'
        tags: ['controller.service_arguments']

    # Autowire des services
    Aropixel\AdminBundle\Email\ResetEmailSender:
        autowire: true

    Aropixel\AdminBundle\Menu\AbstractMenuListener:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Generator\RandomnessGenerator:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Generator\RandomnessGeneratorInterface:
        alias: Aropixel\AdminBundle\Generator\RandomnessGenerator

    # Autowire des services
    Aropixel\AdminBundle\Repository\UserRepository:
        tags: ['doctrine.repository_service']

    # Autowire des services
    Aropixel\AdminBundle\Security\ActivationEmailSender:
        autowire: true

    Aropixel\AdminBundle\Security\ActivationEmailSenderInterface:
        alias: Aropixel\AdminBundle\Security\ActivationEmailSender

    # Autowire des services
    Aropixel\AdminBundle\Security\PasswordCreateHandler:
        autowire: true

    Aropixel\AdminBundle\Security\PasswordCreationHandlerInterface:
        alias: Aropixel\AdminBundle\Security\PasswordCreateHandler

    # Autowire des services
    Aropixel\AdminBundle\Security\ActivationLinkFactory:
        autowire: true

    Aropixel\AdminBundle\Security\ActivationLinkFactoryInterface:
        alias: Aropixel\AdminBundle\Security\ActivationLinkFactory

    # Autowire des services
    Aropixel\AdminBundle\Security\PasswordInitializer:
        autowire: true

    Aropixel\AdminBundle\Security\PasswordInitializerInterface:
        alias: Aropixel\AdminBundle\Security\PasswordInitializer

    # Autowire des services
    Aropixel\AdminBundle\Security\PasswordUpdater:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Security\UniqueTokenGenerator:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Security\UserManager:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Security\LoginFormAuthenticator:
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Services\:
        resource: '../../Services'

    # Autowire des formulaires
    Aropixel\AdminBundle\Form\Type\:
        resource: '../../Form/Type'
        autowire: true

    # Autowire des extensions twig
    Aropixel\AdminBundle\Twig\:
        resource: '../../Twig'


    Aropixel\AdminBundle\Resolver\PathResolver:
        arguments: ['@kernel']

    Aropixel\AdminBundle\Resolver\PathResolverInterface: '@Aropixel\AdminBundle\Resolver\PathResolver'


    Aropixel\AdminBundle\Image\Cropper:
        arguments: ['@Aropixel\AdminBundle\Resolver\PathResolver', '@liip_imagine.data.manager','@liip_imagine.filter.manager','@liip_imagine.cache.manager']


    Aropixel\AdminBundle\EventListener\DoFileCropListener:
        arguments: ['@Aropixel\AdminBundle\Image\Cropper']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }


    Aropixel\AdminBundle\EventListener\UploadImageListener:
        arguments: ['@Aropixel\AdminBundle\Resolver\PathResolver']
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: '%aropixel_admin.entity.image%' }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: '%aropixel_admin.entity.image%' }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: '%aropixel_admin.entity.image%' }
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: '%aropixel_admin.entity.image%' }
            - { name: doctrine.orm.entity_listener, event: postRemove, entity: '%aropixel_admin.entity.image%' }


    Aropixel\AdminBundle\EventListener\UploadFileListener:
        arguments: ['@Aropixel\AdminBundle\Resolver\PathResolver']
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: '%aropixel_admin.entity.file%' }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: '%aropixel_admin.entity.file%' }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: '%aropixel_admin.entity.file%' }
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: '%aropixel_admin.entity.file%' }
            - { name: doctrine.orm.entity_listener, event: postRemove, entity: '%aropixel_admin.entity.file%' }

    Aropixel\AdminBundle\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 30}

    Aropixel\AdminBundle\EventListener\TooOldPasswordEventListener:
        tags:
            - { name: kernel.event_listener, event: 'checkPassport'}

    Aropixel\AdminBundle\EventListener\TooOldLastLoginEventListener:
        tags:
            - { name: kernel.event_listener, event: 'checkPassport' }

    Aropixel\AdminBundle\EventListener\MappedSuperClassSubscriber:
        arguments: ['%aropixel_admin.entities%']
        tags:
            - { name: doctrine.event_subscriber, priority: 8192 }

    Aropixel\AdminBundle\Imagine\Filter\ThumbnailFilter:
        tags:
            - { name: "liip_imagine.filter.loader", loader: upscale_thumbnail }

    Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user_providers'

    Liip\ImagineBundle\Service\FilterService:
        alias: 'liip_imagine.service.filter'

    #####################################################
    ## ROUTER
    #####################################################

    Aropixel\AdminBundle\Router\FrontRouter:
        decorates: router
        arguments: ['@.inner']
