
aropixel_admin_security_first_login_request:
    path:     /activation/first/login
    controller: Aropixel\AdminBundle\Http\Action\First\RequestAction

aropixel_admin_security_first_login_sent:
    path:     /activation/first/login/sent
    controller: Aropixel\AdminBundle\Http\Action\First\EmailSentAction
