image_ajax:
  path: /image/list/ajax
  controller: Aropixel\AdminBundle\Controller\Image\AjaxAction

image_ajax_category:
  path: /image/list/ajax/category
  controller: Aropixel\AdminBundle\Controller\Image\AjaxCategoryAction

image_upload:
  path: /image/upload
  controller: Aropixel\AdminBundle\Controller\Image\UploadAction
  defaults:
    expose: true

image_attach:
  path: /image/attach/image
  controller: Aropixel\AdminBundle\Controller\Image\AttachAction
  defaults:
    expose: true

gallery_attach:
  path: /image/attach/gallery
  controller: Aropixel\AdminBundle\Controller\Image\AttachAction
  defaults:
    expose: true

image_editor:
  path: /image/editor
  controller: Aropixel\AdminBundle\Controller\Image\AttachEditorAction
  defaults:
    expose: true

image_delete:
  path: /image/remove
  controller: Aropixel\AdminBundle\Controller\Image\DeleteAction
  defaults:
    expose: true

image_crop:
  path: /image/crop
  controller: Aropixel\AdminBundle\Controller\Image\CropAction
  defaults:
    expose: true

image_title:
  path: /image/title
  controller: Aropixel\AdminBundle\Controller\Image\TitleAction
  defaults:
    expose: true
