parameters:
    env(ACTIVATION_REQUEST_LIFETIME): 'P1D'
    passwordPeriod: '6 months'
    passwordAttempts: 6
    activationRequestLifeTime: '%env(ACTIVATION_REQUEST_LIFETIME)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    _instanceof:
        Aropixel\AdminBundle\Component\Select2\Select2DataProviderInterface:
            tags: ['aropixel.select2_provider']

    Aropixel\AdminBundle\Http\:
        resource: '../../Http'
        tags: ['controller.service_arguments']

    # Autowire des services
    Aropixel\AdminBundle\Domain\:
        resource: '../../Domain'
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Infrastructure\:
        resource: '../../Infrastructure'
        autowire: true

    # Autowire des services
    Aropixel\AdminBundle\Infrastructure\Security\Passport\Badge\:
        resource: '../../Infrastructure/Security/Passport/Badge'
        autowire: false


    # Autowire des services
    Aropixel\AdminBundle\Infrastructure\User\UserRepository:
        tags: ['doctrine.repository_service']

    Aropixel\AdminBundle\Infrastructure\Media\Image\Library\Repository\ImageRepository:
        tags: ['doctrine.repository_service']



    # Autowire des formulaires
    Aropixel\AdminBundle\Form\Type\:
        resource: '../../Form/Type'

    # Autowire des extensions twig
    Aropixel\AdminBundle\Twig\:
        resource: '../../Twig'

    # Autowire du composant Select2
    Aropixel\AdminBundle\Component\Select2\:
        resource: '../../Component/Select2'
        exclude: '../../Component/Select2/{Select2Interface.php,Select2DataProviderInterface.php,Select2RepositoryInterface.php}'

    Aropixel\AdminBundle\Component\Select2\Select2:
        arguments:
            $providers: !tagged_iterator aropixel.select2_provider

    Aropixel\AdminBundle\Component\Media\Resolver\PathResolverInterface: '@Aropixel\AdminBundle\Component\Media\Resolver\PathResolver'

    Aropixel\AdminBundle\Component\Media\Image\Crop\CropApplierInterface: '@Aropixel\AdminBundle\Component\Media\Image\Crop\CropApplier'


    Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user_providers'

    Liip\ImagineBundle\Service\FilterService:
        alias: 'liip_imagine.service.filter'

    Symfony\Component\DependencyInjection\ContainerInterface:
        alias: 'service_container'
