<?php

namespace Aropixel\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CropRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropRepository extends EntityRepository
{


}
