# SECURITY
sf_web_app_back_office_security:
    resource: "@AropixelAdminBundle/Resources/config/routing/security.yml"

aropixel_reset:
    resource: "@AropixelAdminBundle/Resources/config/routing/reset.yml"

aropixel_admin:
    resource: "@AropixelAdminBundle/Controller/DefaultController.php"
    type:     annotation

aropixel_admin_users:
    resource: "@AropixelAdminBundle/Resources/config/routing/user.yml"

aropixel_admin_images:
    resource: "@AropixelAdminBundle/Controller/ImageController.php"
    type:     annotation

aropixel_admin_files:
    resource: "@AropixelAdminBundle/Controller/FileController.php"
    type:     annotation

aropixel_admin_download_files:
    resource: "@AropixelAdminBundle/Controller/DownloadController.php"
    type:     annotation
