# SECURITY
sf_web_app_back_office_security:
    resource: "@AropixelAdminBundle/Resources/config/routing/security.yml"

aropixel_reset:
    resource: "@AropixelAdminBundle/Resources/config/routing/reset.yml"

_admin:
    path: /
    controller: Aropixel\AdminBundle\Http\Action\Dashboard\DashboardAction

aropixel_admin_users:
    resource: "@AropixelAdminBundle/Resources/config/routing/user.yml"

aropixel_admin_images:
    resource: "@AropixelAdminBundle/Resources/config/routing/image.yml"

aropixel_admin_files:
    resource: "@AropixelAdminBundle/Resources/config/routing/file.yml"
