image_ajax:
  path: /image/list/ajax
  controller: Aropixel\AdminBundle\Http\Action\Image\AjaxAction

image_ajax_category:
  path: /image/list/ajax/{category}
  controller: Aropixel\AdminBundle\Http\Action\Image\AjaxCategoryAction

image_total:
  path: /image/total
  controller: Aropixel\AdminBundle\Http\Action\Image\TotalAction

image_upload:
  path: /image/upload
  controller: Aropixel\AdminBundle\Http\Action\Image\UploadAction
  defaults:
    expose: true

image_attach:
  path: /image/attach/image
  controller: Aropixel\AdminBundle\Http\Action\Image\AttachAction
  defaults:
    expose: true

gallery_attach:
  path: /image/attach/gallery
  controller: Aropixel\AdminBundle\Http\Action\Image\AttachAction
  defaults:
    expose: true

image_editor:
  path: /image/editor
  controller: Aropixel\AdminBundle\Http\Action\Image\AttachEditorAction
  defaults:
    expose: true

image_delete:
  path: /image/remove
  controller: Aropixel\AdminBundle\Http\Action\Image\DeleteAction
  defaults:
    expose: true

image_crop:
  path: /image/crop
  controller: Aropixel\AdminBundle\Http\Action\Image\CropAction
  defaults:
    expose: true

image_crop_save:
  path: /image/save_infos
  controller: Aropixel\AdminBundle\Http\Action\Image\SaveCropAction
  defaults:
    expose: true

image_title:
  path: /image/title
  controller: Aropixel\AdminBundle\Http\Action\Image\SaveCropAction
  defaults:
    expose: true