aropixel_admin_reset_request:
    path:       /reset/request
    controller: Aropixel\AdminBundle\Http\Action\Reset\RequestFormAction

aropixel_admin_request_status:
    path:       /reset/request/status/{status}
    controller: Aropixel\AdminBundle\Http\Action\Reset\RequestStatusAction

aropixel_admin_account_status:
    path:       /reset/account/status/{status}
    controller: Aropixel\AdminBundle\Http\Action\Reset\AccountStatusAction

aropixel_admin_reset_password:
    path:     /reset/{token}/password
    defaults: Aropixel\AdminBundle\Http\Action\Reset\ResetPasswordAction


aropixel_admin_too_old_password_reset_password:
    path:     /reset/old-password/{userId}/password
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetTooOldPassword }

aropixel_admin_too_old_last_login_reset_password:
    path:     /reset/old-login/{userId}
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetTooOldLastLogin }

aropixel_admin_blocked_reset_password:
    path:     /reset/blocked/{userId}
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetBlockedLogin }

