aropixel_admin_reset_request:
    path:     /reset/request
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::requestReset }

aropixel_admin_reset_request_info:
    path:     /reset/request/info
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::requestResetInfo }

aropixel_admin_reset_password:
    path:     /reset/{token}/password
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetPassword }

aropixel_admin_reset_result:
    path:     /reset/success
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetSuccess }

aropixel_admin_too_old_password_reset_password:
    path:     /reset/old-password/{userId}/password
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetTooOldPassword }

aropixel_admin_too_old_password_reset_request_info:
    path:     /reset/old-password/request/info
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::tooOldPasswordResetRequestInfo }

aropixel_admin_too_old_last_login_reset_password:
    path:     /reset/old-login/{userId}
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::resetTooOldLastLogin }

aropixel_admin_too_old_last_login_reset_request_info:
    path:     /reset/old-login/request/info
    defaults: { _controller: Aropixel\AdminBundle\Controller\ResetController::tooOldLastLoginResetRequestInfo }