aropixel_admin_security_login:
    path: /login
    controller: Aropixel\AdminBundle\Http\Action\Security\LoginAction

aropixel_admin_security_logout:
    path:     /logout
    controller: Aropixel\AdminBundle\Http\Action\Security\LogoutAction
