aropixel_admin_security_login:
    path:     /login
    defaults: { _controller: Aropixel\AdminBundle\Controller\SecurityController::login }

aropixel_admin_security_check:
    path:     /login-check
    defaults: { _controller: Aropixel\AdminBundle\Controller\SecurityController::check }
    methods:    [POST]

aropixel_admin_security_logout:
    path:     /logout
    defaults: { _controller: Aropixel\AdminBundle\Controller\SecurityController::logout }